### ISSUE TITLE
Please add an English translation for discoverability

### ISSUE THREAD

**Issue by birdie-github** [Godiesc/compactmodefirefoxcss#1]
CSS rules to make Firefox compact

Steps to apply this theme: copy the Chrome folder and the user.js file into your Firefox profile directory. To find out your profile directory go to about:support or about:profiles.

Additionally, you can use this theme: https://addons.mozilla.org/es/firefox/addon/beautifultotaldark/

**Comment by Godiesc** [comment]
Thanks for the advice, I did it.
